platform :ios, '16.4'

require_relative '../node_modules/react-native/scripts/react_native_pods'

prepare_react_native_project!

target 'AllaweePlus' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add any other pods here

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
      end
    end
  end
end