# Generated by Django 5.2.4 on 2025-08-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_performance_indexes'),
        ('accounts', '0004_add_performance_indexes_sqlite'),
    ]

    operations = [
    ]
